spring:
  application:
    name: zuul-service
server:
  port: 8080
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    audit-service:
      path: /audit/**
      url: AUDIT-SERVICE
    datacollect-service:
      path: /data/**
      url: FORCEDATA-SERVICE
    debit-service:
      path: /debit/**
      url: DEBIT-SERVICE
    credit-service:
      path: /credit/**
      url: CREDIT-SERVICE
    case-process-service:
      path: /process/**
      url: CASE-PROCESS-SERVICE